### PR TITLE
correct value errors

### PR DESCRIPTION
**Pull request by dissolve**

### CODE REVIEW

**Comment by tantek** [comment]
This looks good except for https://github.com/dissolve/tests/blob/1b8f3e1e1b895d81ffc0eb48104e6edd2eb5bbda/tests/microformats-v2/h-card/impliedphoto.html still has a few object/ tags that should be object. Can you take a look and double-check it? I didn't change it in case you had somehow intended to only fix one (of four) instance of that, and if so, I'm curious about the reasoning.

**Comment by dissolve** [comment]
corrections made to that markup @tantek

**Comment by tantek** [comment]
This all looks good to me. Last question(s), do we know if this will add more breakage/passage to other parsers's test results (have you checked)? Or do we have to commit / version / deploy to answer that? Ok with either, we should just know which up front, and move forward with that in mind so we're more clear about next steps.

**Comment by dissolve** [comment]
Currently I don't know of anyone doing automated tests on the system.  The version of the test suite in NPM is way out of date and many of those examples are quite broken.

**Comment by tantek** [comment]
Alright, let's make these fixes and see if we can try latest versions of parsers to see if it improves results (or results in issues to file).

**Pull request merged**
